import type { Metadata } from "next";
import { AuthProvider } from "@/app/context/auth";
import { ThemeProvider } from "@/app/context/theme";

// import { Provider } from 'react-redux';
// import { PersistGate } from 'redux-persist/integration/react';
// import { store, persistor } from '@/app/redux/store';

import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: "Nextjs App",
  description: "Generated by nextjs app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
